#!/usr/bin/env python3
"""Build or check the deterministic repository navigation index."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SECTIONS = [
    ("Canonical framework", "docs", "*.md"),
    ("Decisions", "decisions", "*.md"),
    ("Schemas", "schemas", "*.json"),
    ("Templates", "templates", "*.md"),
    ("Profiles", "profiles", "*.md"),
    ("Automation contracts", "automations", "*.md"),
    ("Workflows", "workflows", "*.md"),
    ("Fictional examples", "examples/fictional", "*"),
    ("Visual descriptions", "visuals/descriptions", "*.md"),
    ("Project records", "project", "*.md"),
    ("Reports", "reports", "*.md"),
]


def title_for(path: Path) -> str:
    if path.suffix == ".md":
        for line in path.read_text(encoding="utf-8").splitlines():
            if line.startswith("# "):
                return line[2:].strip()
    return path.stem.replace("-", " ").title()


def generate(root: Path) -> str:
    lines = [
        "# Repository index",
        "",
        "Generated by `scripts/build_index.py`. Edit source artifacts, then regenerate this file.",
        "",
        "## Primary entry points",
        "",
        "- [Repository overview](README.md)",
        "- [Canonical vocabulary](CONTEXT.md)",
        "- [Governance](GOVERNANCE.md)",
        "- [Validation report](reports/validation-report.md)",
    ]
    for heading, directory, pattern in SECTIONS:
        base = root / directory
        paths = [] if not base.exists() else sorted(path for path in base.rglob(pattern) if path.is_file() and path.name != ".DS_Store")
        if not paths:
            continue
        lines.extend(["", f"## {heading}", ""])
        for path in paths:
            relative = path.relative_to(root).as_posix()
            lines.append(f"- [{title_for(path)}]({relative})")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=ROOT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = args.root.resolve()
    output = generate(root)
    index = root / "INDEX.md"
    if args.check:
        if not index.is_file() or index.read_text(encoding="utf-8") != output:
            print("INDEX.md is stale; run: python3 scripts/build_index.py", file=sys.stderr)
            return 1
        print("INDEX.md is current")
        return 0
    index.write_text(output, encoding="utf-8")
    print(f"updated {index.relative_to(root)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
